### ISSUE TITLE
Array Adapter Issue with single-point masked arrays

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/biggus#192] opened 2016-09-22 12:32 UTC
A bug was spotted in iris in which a single-point array of the type `np.ma.MaskedConstant` is not handled correctly by `iris.util.new_axis` (the resulting mask is not attributed with the new axis when the data is, so the point cannot be transposed;  https://github.com/SciTools/iris/pull/2143).

A temporary fix has been implemented in which the `MaskedConstant` is turned into a `MaskedArray` which is then handled correctly, but this can only apply to loaded data; any lazy data in a single-point array will still be converted to a `MaskedConstant` and not get its extra dimension with `new_axis`.

This requires a fix in Biggus for the lazy data.

**Comment by pelson** [comment] 2017-11-08 06:30
Closing this one out as:

 a) I don't think we are going to fix it, due to our general preference for ``dask.array``
 b) There isn't enough info to reproduce this easily

**Closed by pelson** 2017-11-08 06:30 UTC
